import type { Destination } from "@/lib/data/types";

export const destinations: Destination[] = [
  { slug: "alleppey", name: "Alleppey", region: "domestic", tagline: "Drift through the backwaters",
    story: "Glide along palm-fringed canals on a traditional kettuvallam, past paddy fields, village jetties and slow Kerala afternoons.",
    highlights: ["Overnight houseboat cruise", "Village canoe ride", "Toddy-shop lunch", "Sunset on Vembanad Lake"],
    bestTime: "September to March", image: "/images/alleppey.jpg", map: { x: 128, y: 470, order: 3 } },
  { slug: "munnar", name: "Munnar", region: "domestic", tagline: "Mist, tea and mountain air",
    story: "Rolling tea estates climb into the clouds of the Western Ghats, with waterfalls, spice gardens and cool mornings.",
    highlights: ["Tea museum and estate walk", "Eravikulam National Park", "Mattupetty Dam", "Top Station viewpoint"],
    bestTime: "September to May", image: "/images/munnar.jpg", map: { x: 205, y: 395, order: 2 } },
  { slug: "thekkady", name: "Thekkady", region: "domestic", tagline: "Spice trails and wild elephants",
    story: "Cruise Periyar Lake at dawn for elephants and bison, then walk through cardamom and pepper plantations.",
    highlights: ["Periyar Lake boat safari", "Spice plantation tour", "Kathakali and Kalari shows", "Bamboo rafting"],
    bestTime: "October to June", image: "/images/thekkady.jpg", map: { x: 215, y: 520, order: 4 } },
  { slug: "kovalam", name: "Kovalam", region: "domestic", tagline: "Crescent beaches at land's end",
    story: "Lighthouse views, Ayurvedic retreats and warm Arabian Sea waters at the southern tip of Kerala.",
    highlights: ["Lighthouse Beach", "Ayurveda spa day", "Poovar estuary cruise", "Fresh seafood dinners"],
    bestTime: "October to March", image: "/images/kovalam.jpg", map: { x: 185, y: 700, order: 5 } },
  { slug: "kochi", name: "Kochi", region: "domestic", tagline: "Where the spice routes began",
    story: "Chinese fishing nets, colonial lanes, art cafes and the Biennale: Kerala's port city and our home.",
    highlights: ["Fort Kochi heritage walk", "Chinese fishing nets", "Mattancherry Palace", "Jew Town"],
    bestTime: "October to March", image: "/images/kochi.jpg", map: { x: 112, y: 420, order: 1 } },
  { slug: "wayanad", name: "Wayanad", region: "domestic", tagline: "Forests, caves and coffee",
    story: "Misty plateaus, ancient caves and plantation stays in Kerala's green north.",
    highlights: ["Edakkal Caves", "Chembra Peak trek", "Banasura Sagar Dam", "Plantation stay"],
    bestTime: "October to May", image: "/images/wayanad.jpg", map: { x: 120, y: 150, order: 0 } },
  { slug: "goa", name: "Goa", region: "domestic", tagline: "Sun, sand and susegad", story: "Beaches, Portuguese churches and long lazy evenings.", highlights: ["North Goa beaches", "Old Goa churches", "Dudhsagar Falls"], bestTime: "November to February", image: "/images/goa.jpg" },
  { slug: "andaman", name: "Andaman", region: "domestic", tagline: "Turquoise island escapes", story: "Coral reefs, white sand and island hopping in the Bay of Bengal.", highlights: ["Radhanagar Beach", "Scuba at Havelock", "Cellular Jail"], bestTime: "October to May", image: "/images/andaman.jpg" },
  { slug: "kashmir", name: "Kashmir", region: "domestic", tagline: "Paradise on earth", story: "Shikaras on Dal Lake, meadows of Gulmarg and snow-capped Himalaya.", highlights: ["Dal Lake shikara", "Gulmarg gondola", "Pahalgam valleys"], bestTime: "March to October", image: "/images/kashmir.jpg" },
  { slug: "rajasthan", name: "Delhi, Agra & Jaipur", region: "domestic", tagline: "The Golden Triangle", story: "Forts, palaces and the Taj Mahal on India's classic circuit.", highlights: ["Taj Mahal", "Amber Fort", "Old Delhi food walk"], bestTime: "October to March", image: "/images/rajasthan.jpg" },
  { slug: "bali", name: "Bali", region: "international", tagline: "Temples and rice terraces", story: "Ubud's jungle, cliff temples and island sunsets.", highlights: ["Ubud rice terraces", "Uluwatu temple", "Nusa Penida"], bestTime: "April to October", image: "/images/bali.jpg" },
  { slug: "maldives", name: "Maldives", region: "international", tagline: "Overwater everything", story: "Private villas over lagoons and reefs you can snorkel from your deck.", highlights: ["Overwater villa", "Reef snorkelling", "Sandbank dinner"], bestTime: "November to April", image: "/images/maldives.jpg" },
  { slug: "dubai", name: "Dubai", region: "international", tagline: "Desert meets skyline", story: "Dunes, souks and the world's tallest tower.", highlights: ["Burj Khalifa", "Desert safari", "Dhow cruise"], bestTime: "November to March", image: "/images/dubai.jpg" },
  { slug: "thailand", name: "Thailand", region: "international", tagline: "Islands and street food", story: "Bangkok's energy and Phuket's beaches, with our own Bangkok office on hand.", highlights: ["Phi Phi islands", "Bangkok temples", "Floating markets"], bestTime: "November to April", image: "/images/thailand.jpg" },
  { slug: "vietnam", name: "Vietnam", region: "international", tagline: "Bays, lanterns and pho", story: "Ha Long Bay cruises and the lantern-lit streets of Hoi An.", highlights: ["Ha Long Bay", "Hoi An old town", "Hanoi street food"], bestTime: "February to April", image: "/images/vietnam.jpg" },
  { slug: "europe", name: "Europe", region: "international", tagline: "Grand tour, your way", story: "Paris, Swiss Alps and Italian cities on a guided group tour.", highlights: ["Eiffel Tower", "Jungfraujoch", "Venice gondola"], bestTime: "April to September", image: "/images/europe.jpg" },
];
