import type { Package } from "@/lib/data/types";

// All packages are draft placeholder copy pending client review; pricing omitted until confirmed.
export const packages: Package[] = [
  { slug: "kerala-classic-6d", title: "Kerala Classic", destinationSlugs: ["kochi", "munnar", "thekkady", "alleppey"], region: "domestic", durationDays: 6, holidayTypes: ["family", "honeymoon"], featured: true, draft: true,
    summary: "Kochi heritage, Munnar tea hills, Thekkady spice trails and a night on the backwaters.",
    itinerary: [
      { day: 1, title: "Arrive Kochi", blurb: "Fort Kochi walk and sunset at the fishing nets." },
      { day: 2, title: "Kochi to Munnar", blurb: "Drive up via Cheeyappara waterfalls." },
      { day: 3, title: "Munnar", blurb: "Eravikulam, tea museum and Mattupetty." },
      { day: 4, title: "Munnar to Thekkady", blurb: "Spice plantation tour and cultural show." },
      { day: 5, title: "Thekkady to Alleppey", blurb: "Board your private houseboat for an overnight cruise." },
      { day: 6, title: "Depart", blurb: "Disembark and transfer to Kochi airport." },
    ],
    inclusions: ["Hotels and houseboat", "Breakfast daily, all meals on houseboat", "Private AC car with driver", "Airport transfers"],
    image: "/images/munnar.jpg" },
  { slug: "backwater-honeymoon-4d", title: "Backwater Honeymoon", destinationSlugs: ["munnar", "alleppey"], region: "domestic", durationDays: 4, holidayTypes: ["honeymoon", "houseboat"], featured: true, draft: true,
    summary: "Two misty days in Munnar and a candlelit night on a private houseboat.",
    itinerary: [
      { day: 1, title: "Kochi to Munnar", blurb: "Check in to a valley-view resort." },
      { day: 2, title: "Munnar", blurb: "Top Station, tea estates and couple's spa." },
      { day: 3, title: "Alleppey houseboat", blurb: "Private cruise with candlelight dinner." },
      { day: 4, title: "Depart", blurb: "Transfer to Kochi." },
    ],
    inclusions: ["Honeymoon decor", "Private houseboat", "Breakfast and houseboat meals", "Private car"], image: "/images/alleppey.jpg" },
  { slug: "kerala-beaches-ayurveda-5d", title: "Beaches & Ayurveda", destinationSlugs: ["alleppey", "kovalam"], region: "domestic", durationDays: 5, holidayTypes: ["family"], draft: true,
    summary: "Backwaters followed by three slow days of beach and Ayurveda in Kovalam.",
    itinerary: [
      { day: 1, title: "Arrive Kochi, drive to Alleppey", blurb: "Lakeside resort and canoe ride." },
      { day: 2, title: "Alleppey to Kovalam", blurb: "Coastal drive south." },
      { day: 3, title: "Kovalam", blurb: "Lighthouse Beach and Ayurveda session." },
      { day: 4, title: "Poovar", blurb: "Estuary cruise to the golden sand bar." },
      { day: 5, title: "Depart", blurb: "Transfer to Trivandrum airport." },
    ],
    inclusions: ["Hotels", "Breakfast daily", "One Ayurveda session", "Private car"], image: "/images/kovalam.jpg" },
  { slug: "kashmir-paradise-6d", title: "Kashmir Paradise", destinationSlugs: ["kashmir"], region: "domestic", durationDays: 6, holidayTypes: ["family", "honeymoon"], featured: true, draft: true,
    summary: "Houseboat on Dal Lake, Gulmarg meadows and Pahalgam valleys.",
    itinerary: [
      { day: 1, title: "Arrive Srinagar", blurb: "Shikara ride and houseboat stay." },
      { day: 2, title: "Gulmarg", blurb: "Gondola ride." },
      { day: 3, title: "Pahalgam", blurb: "Betaab and Aru valleys." },
      { day: 4, title: "Sonamarg", blurb: "Thajiwas glacier." },
      { day: 5, title: "Srinagar", blurb: "Mughal gardens." },
      { day: 6, title: "Depart", blurb: "Airport transfer." },
    ],
    inclusions: ["Hotels and houseboat", "Breakfast and dinner", "Private car"], image: "/images/kashmir.jpg" },
  { slug: "andaman-islands-5d", title: "Andaman Island Hop", destinationSlugs: ["andaman"], region: "domestic", durationDays: 5, holidayTypes: ["adventure", "family"], draft: true,
    summary: "Port Blair history, Havelock beaches and a first dive.",
    itinerary: [
      { day: 1, title: "Port Blair", blurb: "Cellular Jail light and sound show." },
      { day: 2, title: "Havelock", blurb: "Ferry and Radhanagar sunset." },
      { day: 3, title: "Havelock", blurb: "Try scuba at Elephant Beach." },
      { day: 4, title: "Neil Island", blurb: "Natural bridge and Bharatpur beach." },
      { day: 5, title: "Depart", blurb: "Return ferry and flight." },
    ],
    inclusions: ["Hotels", "Ferries", "Breakfast", "Transfers"], image: "/images/andaman.jpg" },
  { slug: "bali-escape-6d", title: "Bali Escape", destinationSlugs: ["bali"], region: "international", durationDays: 6, holidayTypes: ["honeymoon", "adventure"], featured: true, draft: true,
    summary: "Ubud jungle villas, Kintamani volcano and Nusa Penida cliffs.",
    itinerary: [
      { day: 1, title: "Arrive Bali", blurb: "Seminyak sunset." },
      { day: 2, title: "Ubud", blurb: "Rice terraces and swing." },
      { day: 3, title: "Kintamani", blurb: "Volcano views and coffee plantation." },
      { day: 4, title: "Nusa Penida", blurb: "Kelingking and Broken Beach." },
      { day: 5, title: "Uluwatu", blurb: "Temple and Kecak dance." },
      { day: 6, title: "Depart", blurb: "Airport transfer." },
    ],
    inclusions: ["Hotels", "Breakfast", "Tours with guide", "Transfers"], image: "/images/bali.jpg" },
  { slug: "maldives-overwater-4d", title: "Maldives Overwater", destinationSlugs: ["maldives"], region: "international", durationDays: 4, holidayTypes: ["honeymoon"], featured: true, draft: true,
    summary: "Three nights in an overwater villa with reef snorkelling.",
    itinerary: [
      { day: 1, title: "Arrive Male", blurb: "Speedboat to resort." },
      { day: 2, title: "Reef day", blurb: "Snorkel and sandbank picnic." },
      { day: 3, title: "At leisure", blurb: "Spa and sunset dolphin cruise." },
      { day: 4, title: "Depart", blurb: "Transfer to Male." },
    ],
    inclusions: ["Overwater villa", "Half board", "Speedboat transfers"], image: "/images/maldives.jpg" },
  { slug: "dubai-highlights-5d", title: "Dubai Highlights", destinationSlugs: ["dubai"], region: "international", durationDays: 5, holidayTypes: ["family", "group"], draft: true,
    summary: "Burj Khalifa, desert safari and a dhow cruise dinner.",
    itinerary: [
      { day: 1, title: "Arrive Dubai", blurb: "Dhow cruise dinner." },
      { day: 2, title: "City tour", blurb: "Burj Khalifa and Dubai Mall." },
      { day: 3, title: "Desert safari", blurb: "Dune bashing and BBQ camp." },
      { day: 4, title: "Abu Dhabi", blurb: "Grand Mosque day trip." },
      { day: 5, title: "Depart", blurb: "Airport transfer." },
    ],
    inclusions: ["Hotel", "Breakfast", "Tours", "Visa assistance"], image: "/images/dubai.jpg" },
  { slug: "thailand-group-6d", title: "Thailand Group Tour", destinationSlugs: ["thailand"], region: "international", durationDays: 6, holidayTypes: ["group"], featured: true, draft: true,
    summary: "Bangkok and Pattaya with our Bangkok team on the ground.",
    itinerary: [
      { day: 1, title: "Arrive Bangkok", blurb: "Transfer to Pattaya." },
      { day: 2, title: "Coral Island", blurb: "Speedboat and beach." },
      { day: 3, title: "Pattaya", blurb: "Nong Nooch garden." },
      { day: 4, title: "Bangkok", blurb: "Temples and river cruise." },
      { day: 5, title: "Safari World", blurb: "Marine park." },
      { day: 6, title: "Depart", blurb: "Airport transfer." },
    ],
    inclusions: ["Hotels", "Breakfast", "Indian meals", "Tour manager"], image: "/images/thailand.jpg" },
  { slug: "vietnam-discovery-7d", title: "Vietnam Discovery", destinationSlugs: ["vietnam"], region: "international", durationDays: 7, holidayTypes: ["cruise", "adventure"], draft: true,
    summary: "Hanoi, an overnight Ha Long Bay cruise and lantern-lit Hoi An.",
    itinerary: [
      { day: 1, title: "Hanoi", blurb: "Old Quarter food walk." },
      { day: 2, title: "Ha Long Bay", blurb: "Board overnight cruise." },
      { day: 3, title: "Ha Long Bay", blurb: "Kayaking and caves, return to Hanoi." },
      { day: 4, title: "Fly to Da Nang", blurb: "Ba Na Hills Golden Bridge." },
      { day: 5, title: "Hoi An", blurb: "Lantern night market." },
      { day: 6, title: "My Son", blurb: "Ancient Cham temples." },
      { day: 7, title: "Depart", blurb: "Airport transfer." },
    ],
    inclusions: ["Hotels and cruise", "Breakfast", "Domestic flight", "Guided tours"], image: "/images/vietnam.jpg" },
  { slug: "europe-grand-tour-10d", title: "Europe Grand Tour", destinationSlugs: ["europe"], region: "international", durationDays: 10, holidayTypes: ["group", "family"], draft: true,
    summary: "Paris, Switzerland and Italy with an escorted group.",
    itinerary: [
      { day: 1, title: "Paris", blurb: "Arrival and Seine cruise." },
      { day: 2, title: "Paris", blurb: "Eiffel Tower and Louvre." },
      { day: 3, title: "To Switzerland", blurb: "Drive to Lucerne." },
      { day: 4, title: "Jungfraujoch", blurb: "Top of Europe." },
      { day: 5, title: "Lucerne", blurb: "Mt Titlis." },
      { day: 6, title: "To Venice", blurb: "Gondola ride." },
      { day: 7, title: "Florence and Pisa", blurb: "Leaning tower." },
      { day: 8, title: "Rome", blurb: "Colosseum." },
      { day: 9, title: "Vatican", blurb: "St Peter's Basilica." },
      { day: 10, title: "Depart", blurb: "Fly home." },
    ],
    inclusions: ["Hotels", "Breakfast and Indian dinners", "Coach travel", "Tour manager", "Visa assistance"], image: "/images/europe.jpg" },
  { slug: "kerala-houseboat-2d", title: "Houseboat Getaway", destinationSlugs: ["alleppey"], region: "domestic", durationDays: 2, holidayTypes: ["houseboat", "family", "cruise"], draft: true,
    summary: "A one-night private kettuvallam cruise on Vembanad Lake.",
    itinerary: [
      { day: 1, title: "Board at noon", blurb: "Cruise with Kerala lunch, tea and dinner on board." },
      { day: 2, title: "Disembark", blurb: "Breakfast and checkout by 9am." },
    ],
    inclusions: ["Private houseboat", "All meals on board", "Transfers from Kochi"], image: "/images/type-houseboat.jpg" },
];
